config/routes.rb
RecipeBookApp::Application.routes.draw do
  resources :recipes
  resources :categories
  resources :ingredients

  root to: "recipes#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :recipes
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :calories, :image, :name, :unit, :quantity

 has_many :ingredients, through: :ingredients_recipes
 has_many :ingredients_recipes
  

end

app/models/ingredients_recipe.rb
class IngredientsRecipe < ActiveRecord::Base
  attr_accessible :ingredient_id, :quantity, :recipe_id

  belongs_to :ingredient
  belongs_to :recipe

  
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :description, :feeds, :image, :name, :time, :category_id, :ingredient_ids

  belongs_to :category
  has_many :ingredients, through: :ingredients_recipes
  has_many :ingredients_recipes

  accepts_nested_attributes_for :ingredients_recipes
  validates :name, presence: true
  validates :name, length: {minimum: 2}
  validates :name, length: {maximum: 20}
  validates :ingredient_ids, presence: true

 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController 
  
  def index
    @categories = Category.all
    @recipes = Recipe.all
    redirect_to recipes_path
  end

  def show
    @category = Category.find_by_id(params[:id])
  end

  def edit 
    @category = Category.find_by_id(params[:id])
  end

  def update
    Category.find_by_id(params["id"]).update_attributes(params["category"])
    redirect_to categories_path
  end

  def create
    Category.create(params["category"])
    redirect_to categories_path
  end

  def new
    @category = Category.new
  end

  def destroy
    Category.find_by_id(params[:id]).destroy
    redirect_to categories_path
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController 

  def index
    @ingredients = Ingredient.all
  end

  def show
    @ingredient = Ingredient.find_by_id(params[:id])
  end

  def edit 
    @ingredient = Ingredient.find_by_id(params[:id])
  end

  def update
    Ingredient.find_by_id(params["id"]).update_attributes(params["ingredient"])
    redirect_to ingredients_path
  end

  def create
    Ingredient.create(params["ingredient"])
    redirect_to ingredients_path
  end

  def new
    @ingredient = Ingredient.new
  end

  def destroy
    Ingredient.find_by_id(params[:id]).destroy
    redirect_to ingredients_path
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController 

  def index
    @categories = Category.all
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find_by_id(params[:id])
  end

  def edit 
    @recipe = Recipe.find_by_id(params[:id])
    @ingredients = Ingredient.all
  end

  def update
    to_add = params["recipe"]
    to_add["ingredient_ids"] = params["ingredient_ids"]
    @recipe = Recipe.find_by_id(params["id"])
    @recipe.update_attributes(to_add)

    quantity_to_add = params["quantity"]
    

    @recipe.ingredient_ids.each do |id|
      i = IngredientsRecipe.where(recipe_id: @recipe.id, ingredient_id: id).first
      i.quantity = quantity_to_add[id.to_s]
      i.save
    end
    
    @ingredients = Ingredient.all
        
      if  @recipe.errors.count == 0
        
        redirect_to recipe_path(@recipe)  

      else

        render action: "edit" 
              
      end
   
  end

  def create
    @recipe = Recipe.create(params["recipe"])
    @recipe.ingredient_ids = params["ingredient_ids"]
    @ingredients = Ingredient.all
      if @recipe.save
        redirect_to recipe_path(@recipe) 
      else
        render action: "new" 

      end
  end

  def new
    @recipe = Recipe.new
    @ingredients = Ingredient.all
  end

  def destroy
    Recipe.find_by_id(params[:id]).destroy
    redirect_to recipes_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper

  def list_ingredients
    output = []
   @recipe.ingredient_ids.each do |ingredient_id|
        quantity = IngredientsRecipe.where(recipe_id: @recipe.id, ingredient_id: ingredient_id).first.quantity
        if quantity 
           output << quantity.to_s + " " + Ingredient.find(ingredient_id).name
        else 
           output << "some " + Ingredient.find(ingredient_id).name 
        end   
    end
    output = output.to_sentence
    output[0] = output[0].capitalize
    output
 
  end

  def quantity(ingredient)
    a = IngredientsRecipe.where(recipe_id: @recipe.id, ingredient_id: ingredient.id).first
    a.quantity if a
  end

  def error_msg(field)
    case field 
    when :name
      @recipe.errors[:name].first.capitalize unless @recipe.errors[:name].count == 0
    when :ingredient_ids
      if @recipe.errors[:ingredient_ids].count > 0 then 'You have to pick at least one ingredient for your recipe.' end
    else 
      ""  
    end  
  end


end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  Name: <%= f.text_field :name%>
  <%= f.submit "submit" %>
<% end %>

app/views/categories/_list_recipes.html.erb
<% recipes = Recipe.where(category_id: category_id) %>
  <table>
  <% recipes.each do |recipe| %>

    <tr>

      <td><a href="<%= recipe_path(recipe) %>"><%= recipe.name %></a></td>
    
      <td><%= button_to 'Delete', recipe_path(recipe), :method => :delete %></td>
      <td><%= button_to 'Edit', edit_recipe_path(recipe), :method => :get %></td>
    </tr>

  <% end %>
  </table>

  

app/views/categories/create.html.erb
<h2>Create a category</h2>
<%= render "form" %>

app/views/categories/edit.html.erb
<h2>Edit a catgory</h2>
<%= render "form" %>

app/views/categories/index.html.erb
<% @categories.each do |category| %>

  <h2><%= category.name %></h2>
  
  <%= render partial: 'list_recipes', locals: {category_id: category.id} %> 

 <% end %>

app/views/categories/new.html.erb
<h2>Create a category</h2>
<%= render "form" %>

app/views/categories/show.html.erb
<div class="category_show">
<h2><%= "#{@category.name.pluralize}" %></h2>
<%= button_to 'Delete', category_path(@category), :method => :delete %>
<%= button_to 'Edit', edit_category_path(@category), :method => :get %> 


<%= render partial: 'list_recipes', locals: {category_id: @category.id} %>   

</div>

app/views/ingredients/_form.html.erb
<div class="ingredients_new">
<%= form_for @ingredient do |f| %>
  Name: <%= f.text_field :name%>
  <%= f.submit "submit" %>
<% end %>
</div>

app/views/ingredients/_list_recipes.html.erb
<% recipes = Recipe.where(category_id: category_id) %>
  <ul>
  <% recipes.each do |recipe| %>

    <li>
      <a href="<%= recipe_path(recipe) %>"><%= recipe.name %></a>
      <%= button_to 'Delete', recipe_path(recipe), :method => :delete %>
      <%= button_to 'Edit', edit_recipe_path(recipe), :method => :get %>
    </li>

  <% end %>
  </ul>

  

app/views/ingredients/edit.html.erb
<h2>Edit an Ingredient</h2>

<%= render "form" %>

app/views/ingredients/index.html.erb
<h2>List of ingredients</h2>

<table class="ingredients_list">
<% @ingredients.each do |ingredient| %>
  <tr>
    <td><%= ingredient.name %></td>
    <td><%= button_to 'Delete', ingredient_path(ingredient), :method => :delete %></td>
    <td><%= button_to 'Edit', edit_ingredient_path(ingredient), :method => :get %></td>
  </tr>
 <% end %>
</table>

<%= button_to 'Add an ingredient', new_ingredient_path, :method => :get %>

app/views/ingredients/new.html.erb
<h2>Create an ingredient</h2>
<%= render "form" %>

app/views/ingredients/show.html.erb
<p><%= "#{@ingredient.name}"</p>   


<%= button_to 'Delete', recipe_path(@ingredient), :method => :delete %>
<%= button_to 'Edit', edit_recipe_path(@ingredient), :method => :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipeBookApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
 <link href='http://fonts.googleapis.com/css?family=Spinnaker' rel='stylesheet' type='text/css'>
 <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-36647147-3', 'mike-ga-project-vhs-tube.herokuapp.com');
  ga('send', 'pageview');

</script>
</head>
<body>
<main>
<h1><a href="/"> Mike's Cookbook</a></h1>
<nav>
  <a href="<%= new_recipe_path %>">New Recipe</a>
  <a href="<%= new_category_path %>">New Category</a>
  <a href="<%= ingredients_path %>">Manage Ingredients</a>
</nav>
<%= yield %>
</main>
</body>
</html>

app/views/recipes/_form.html.erb
<% @recipe.errors.full_messages %>


<div class="recipe_form">
<table>
<%= form_for @recipe do |f| %>
  <tr>
    <td>Name:</td> <td><%= f.text_field :name%></td><td><%= error_msg(:name) %>
  
  <tr>  
    <td>Feeds:</td> <td><%= f.text_field :feeds %></td>
  </tr>
  <tr>
    <td>Time:</td> <td><%= f.text_field :time %></td>
  </tr>
  <tr>
    <td>Description:</td> <td><%= f.text_area :description, size: "40x12" %></td>
  </tr>
  <tr>
    <td>
      Category:
    </td>
    <td><%= select_tag 'recipe[category_id]', options_from_collection_for_select(Category.all, 'id', 'name') %></td>
  </tr>
  <tr>
    <td>
      Ingredients:
    </td>
    <td class="checkboxes<%= if @recipe.errors[:ingredient_ids].count > 0 then 'field_with_errors' end %>" >
      
      <% @ingredients.each_with_index do |ingredient, j| %>
      
       <%= label_tag( "ingredient_ids[]", ingredient.name) %>
        <%= check_box_tag("ingredient_ids[]", ingredient.id, if  @recipe.ingredient_ids.include?(ingredient.id) then checked = true end, class: "check" + j.to_s) %>
        <% if (j +1) % 4 == 0 %> <br /> <% end %>

       
      
      <% end %>
      <!-- </td>
      <td class="checkboxes"> -->
        
        </br> Quantity:</br></br> 

      <% @ingredients.each_with_index do |ingredient , i| %>
        <div class="ingredient<%= i.to_s %> hidebox">

        <div class="ing_name"><%= ingredient.name.capitalize %> (<%= ingredient.unit %>)</div> <%= text_field "quantity" , ingredient.id , value: quantity(ingredient)  %> <br />
        
        </div>
      <% end %>

      </td>
      <td>
        <%= error_msg(:ingredient_ids) %>
      </td>

  </tr>

  <tr>
    <td></td><td><%= f.submit "submit" %></td>
  </tr>




<% end %>
</table>
<div>

app/views/recipes/_list_recipes.html.erb
<% recipes = Recipe.where(category_id: category_id) %>
  <table>
  <% recipes.each do |recipe| %>

    <tr>

      <td><a href="<%= recipe_path(recipe) %>"><%= recipe.name %></a></td>
    
      <td><%= button_to 'Delete', recipe_path(recipe), :method => :delete %></td>
      <td><%= button_to 'Edit', edit_recipe_path(recipe), :method => :get %></td>
    </tr>

  <% end %>
  </table>

  

app/views/recipes/edit.html.erb
<h2>Edit a recipe</h2>

<%= render "form" %>

app/views/recipes/index.html.erb
<div class="list_recipes">
<% @categories.each do |category| %>

  <h2><a href="<%= category_path(category) %>"><%= category.name.pluralize %></a></h2>

  <%= render partial: 'list_recipes', locals: {category_id: category.id} %> 

 <% end %>

<% unless Recipe.where(category_id: nil).count == 0 %>
  <h2>Recipes with no Category</h2>


    <%= render partial: 'list_recipes', locals: {category_id: nil} %> 
  <% end %>
</div>

app/views/recipes/new.html.erb
<h2>Create a recipe</h2>
<%= render "form" %>

app/views/recipes/show.html.erb
<h2><%= @recipe.name %></h2>

 <table class = "recipe_show">


  <tr>  
    <td>Feeds:</td> <td><%= @recipe.feeds %></td>
  </tr>
  <tr>
    <td>Time:</td> <td><%= @recipe.time %></td>
  </tr>
  <tr>
    <td>Description:</td> <td><%= @recipe.description %></td>
  </tr>
  <tr>
    <td>
      Category:
    </td>
    <td><%= @recipe.category.name unless @recipe.category.nil? %></td>
  </tr>
  <tr>
    <td>
      Ingredients:
    </td>
    <td>
        
       <%= list_ingredients %>

            
      
      </td>
  </tr>

</table>
<%= button_to 'Delete', recipe_path(@recipe), :method => :delete %>
<%= button_to 'Edit', edit_recipe_path(@recipe), :method => :get %>